---
title: Power analysis in experimental design
author: Obryan Poyser
date: '2018-07-15'
slug: power-analysis-in-experimental-design
categories:
  - Statistics
tags:
  - Power Analysis
  - R
type: post
description: ""
keywords:
  - key
  - words
topics:
  - topic 1
bibliography: allrefs.bib
---

A couple of weeks ago we had hour yearly Ph.D. workshop in which we present our project development. I've always moral sentiments around my duties regarding what someone as me who received a grant should do. One of these moral burden is to assist to every single presentation and try to provide useful feedback.

Long story short, a fellow Ph.D. student presented a draft of a experimental design. Aligned with my principles, I suggested her to be more humble regarding what she wanted to test, since there were far too many hypothesis she wanted to test for (i.e. treatments) which certainly would limit her sample within and between groups. As a consequence, she replied: *How big do you think my sample should be?*, to be honest, I couldn't provide her with a exact answer, this post is a result of my deficient feedback.

Experiments have been increasing in popularity in economics, as a effect of the "empirical revolution" trending as a whole as well as an increasing criticism on identification assumptions when the objective is to find a causal effect in observational data. Indeed, experiments let us identify a cause for a certain phenomena easier, nevertheless, the design as well as the cost of realizing a experiment is not negligible. If something ends bad, most probably we won't have the same resources and opportunity to rerun it, hence, we must be careful to design an experiment that maximize our testing expectatives. 

Finding the optimal sample size is definitely one of the main concerns a researcher should have when she designs an experiment. For this matter, there exist the so-called **Power Analysis**, a process of estimating the minimum (optimal) sample size needed to detect an effect given a treatment at a desirable significance level.  

@List2011[] argue that there are three main aspects we should consider in order to calculate the optimal sample size.

1. Significance level
1. Power
1. Minimum detectable effect size

So, let's start by talking about significance level, by bringing back what we learned in statistics 101 about hypothesis testing:

+ Type I: Probability of rejecting the null hypothesis given that it is true (false positive)  
$$P(R|H_0=true)$$
+ Type II: Probability of not rejecting (accepting duh) the null hypothesis given that it is false (false negative)
$$P(A|H_0=false)$$
and Type II error described by: 



### References