---
title: Still searching
author: Obryan Poyser
date: '2018-07-19'
slug: still-searching
categories:
  - Personal
tags:
  - Music
type: post
description: ""
keywords:
  - key
  - words
topics:
  - topic 1
lang:
  - english
---

<iframe width="560" height="315" src="https://www.youtube.com/embed/YsunfX4FwHM" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>


Some girl in the twinkling of an eye
Dem ah ready fi come pull down me Karl Kani
Oh come on now
Tell me how can I
Love ah one dat really don't deserve me
Na try fi keep and na try preserve me
Me's ah boy could get whole heep ah girl ya heard me
Many are called but only few deemed worthy
Body have to physically strong and sturdy
Spiritually balanced fi come clean and purge me
Mentally advanced fi always urge me
Read a couple books and challenge the clergy
Read a couple psalms up in the morning early

Could you be so kind
Then so me a sign
I've been searching and it's so hard to find
Decent values with a decent wine
Decent jubee running it down the line
Maybe it's my mind
Maybe I'm blind
Maybe it's the way that I've been spending my time
I'm still searching for a fine peace of mind
Decent jubee running it down the line

A little child has grown
And he's got love on his mind
But what he'll never know
A virtuous woman is hard to find

And dat's when she said
She feels the pain
And she'll never fall
In love again

So if you is a gyal wit whole heep of value
What a valuable nice and decent gyal you
When I get you I'll be glad I got you
Then stand firmly inna your life like statue
Seen some old things seen some young things
Seen some little silly go and come things
Seen some one night just for fun things
What a indecent piece ah some things

Be so kind
Then show me a sign
I've been searching and it's so hard to find
Decent values with a decent wine
Decent jubee running it down the line
Maybe it's my mind
Maybe I'm blind
Maybe it's the way I've been spending my time
I'm still searching for a fine peace of mind
Decent jubee running it down the line

Some say that love is blind
But he keep saying not this time
So all he need is love
To keep his heart in line

But that's when she said
She feels the pain
And she'll never fall
In love again

You have some gyal ah come pon man premises
And ah fling up the ting that's between di knees
And ah up man with his false promises
Oh dutty bungle please
Couldn't want to run that so fast with ease
been there done that my main squeeze is natural
simply natural

Would you be so kind
Then show me a sign
I've been searching and it's so hard to find
Decent values with a decent wine
Decent jubee running it down the line
Maybe it's my mind
Maybe I'm blind
Maybe it's the way I've been spending my time
I'm still searching for a fine peace of mind
Decent jubee running it down the line

A little child has grown
And he's got love on his mind
But what he'll never know
A virtuous woman is hard to find

Cause that's when she said she's feeling pain
It seems they have fallen in love again
That's when she said
Lord I feel the pain
And now they're standing in love again

So tell me ah when price tag gone pon annany
Gyal ah love man for Benz and Ferrari
Little one eyed brethren weh name Omari
Couldn't get no loving since him sell stary
Some girl in the twinkling of an eye
Them ah ready fi come pull down mi Karl Kani
Oh come on know
Tell me how can I
Love ah one dat really don't deserve me
